config/routes.rb
Rails.application.routes.draw do



  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  root 'posts#index'

  resources :posts
  resources :users


end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :posts, dependent: :destroy

	validates :email, presence: true
	validates :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	include PostsHelper

	def index
		@latest = Post.all.reverse
	end


	def show
		@post = Post.find_by_id params[:id]
	end


	def new
		if login?
			@post = Post.new
			render 'new'
		else
			redirect_to root_path
		end
	end

	def edit
		@post = Post.find_by_id params[:id]
		if @post.user == current_user
			render 'edit'
		else
			redirect_to '/'
		end
	end


	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id if current_user

		if @post.save
  		redirect_to @post
  	else
  		render 'new'
  	end

	end

	def update
		@post = Post.find_by_id params[:id]

		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find_by_id params[:id]
		if @post.user == current_user
			@post.destroy
			redirect_to current_user
		else
			redirect_to posts_path
		end
	end


	private

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

  def create
    @user = User.find_by_email(params[:email])

    if @user && @user.authenticate(params[:password])

      session[:user_id] = @user.id
      redirect_to @user
    else
      @errors = "Display Name or Password invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id]=nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	include UsersHelper

	def index
		@users = User.all
	end

	def show
		@user = User.find_by_id params[:id]
		@posts = @user.posts
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to @user
		else
			render 'new'
		end
	end


	private

		def user_params
  		params.require(:user).permit(:username, :email, :password)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
  	render '/posts/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def login?
  	User.exists?(session[:user_id])
	end

	def current_user
 	 User.find_by_id params[session[:user_id]] if login?
	end

	def guest_redirect
  	redirect "/login" if !login?
	end

	def authorized_user(user)
  	return true if login? && current_user == user
  	false
	end
end

app/helpers/posts_helper.rb
module PostsHelper
	def login?
  	User.exists?(session[:user_id])
	end

	def current_user
 	 User.find(session[:user_id]) if login?
	end

	def guest_redirect
  	redirect "/login" if !login?
	end

	def authorized_user(user)
  	return true if login? && current_user == user
  	false
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def logged_in?
  	User.exists?(id: session[:user_id])
	end

	def current_user
  	User.find(session[:user_id])
	end
	
end

app/helpers/users_helper.rb
module UsersHelper
	
	def login?
  	User.exists?(session[:user_id])
	end

	def current_user
 	 User.find(session[:user_id]) if login?
	end

	def guest_redirect
  	redirect "/login" if !login?
	end

	def authorized_user(user)
  	return true if login? && current_user == user
  	false
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jared's Blog App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header id="main_navigation" class="clearfix">
		<%= link_to "Jared's Blog App", posts_path, :class => "name" %>

		<nav>
					<%= link_to 'All Posters', users_path %>
			<% if login? %>
					<%= link_to current_user.username, current_user %>
					<%= link_to 'Sign out', logout_path %>
			<% else %>
					<%= link_to 'Sign in', login_path %>
					<%= link_to 'Register', new_user_path %>
			<% end %>
		</nav>
		</header>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being created:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content, cols: "50", rows: "10" %>
  </p>

 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @latest.each do |post| %>
  <div id="posts_show_content" class="skinny_wrapper wrapper_padding">
   <header>
     <p class="posted_by">posted by <a class="posted_by" href="/users/<%= post.user.id %>"><%= post.user.username %></a></p>
     <h1><a id="index_title" href="/posts/<%= post.id %>"><%= post.title %></a></h1>
     <hr>
    </header>
    <div id="content">
      <p><%= post.content.split[0..50].join(" ") %><a style="color: black;" href="/posts/<%= post.id %>">
      . . .read more</a></p>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id='form'>

	<h1>New Post</h1>

	<%= render 'form' %>

	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div id="posts_show_content" class="skinny_wrapper wrapper_padding">
  <header>
  <% if @post %>
     <p class="posted_by">posted by <a class="posted_by" href="/users/<%= @post.user.id %>"><%= @post.user.username %></a></p>
     <h1><%= @post.title %></h1>
     <hr>
    </header>
    <div id="content">
      <p><%= @post.content %></p>
    </div>
    <% if current_user==@post.user %>
        <nav id='post_options'>
          <%= link_to 'Edit', edit_post_path(@post) %> |
          <%= link_to 'Delete ', @post,
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
        </nav>
    <% end %>
    <hr>
    <%= render 'disqus' %>
  <% end %>
</div>

app/views/users/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    /*
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//jaredsblogapp.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being created:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/users/index.html.erb
<div class="wrapper wrapper_padding cleafix">
			
	<div class="col-2 home_content">
		<h2>Find a blog</h2>
		<hr>
		<% @users.each do |user| %>
			<p><a id="index_title" href="/users/<%= user.id %>"><%= user.username %></a></p>
		<% end %>
	</div>

</div>

app/views/users/new.html.erb
<div id='form'>

	<h1>New User</h1>

	<%= render 'form' %>

	<%= link_to 'Back', root_path %>

</div>

app/views/users/show.html.erb
<h1 id="profile-header"><%= @user.username %>'s Blog</h1>

<% if @user == current_user %>
  <span id="new_post"><%= link_to 'New Post', new_post_path %></span>
<% end %>

<% @user.posts.each do |post| %>
  <div id="posts_show_content" class="skinny_wrapper wrapper_padding">
   <header>
     <p class="posted_by">posted by <%= post.user.username %></p>
     <h1><a id="index_title" href="/posts/<%= post.id %>"><%= post.title %></a></h1>
     <hr>
    </header>
    <div id="content">
      <p><%= post.content.split[0..50].join(" ") %><a style="color: black;" href="/posts/<%= post.id %>">
      . . .read more</a></p>
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
		<div class="wrapper wrapper_padding cleafix">
			
			<div class="col-1 home_content">
				<h2>About</h2>
				<hr>
				<p>About this blog</p>
				<p>More about this blog</p>
			</div>

			<div class="col-2 home_content">
				<h2>Other things</h2>
				<hr>
				<p>About this blog</p>
				<p>More about this blog</p>
			</div>
			
			<div class="col-3 home_content">
				<h2>Some Final things</h2>
				<hr>
				<p>About this blog</p>
				<p>More about this blog</p>
			</div>	

		</div>